# Generated by Django 5.0.6 on 2024-06-25 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_follow', models.DateField(auto_now_add=True)),
                ('followed_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL
                    )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL
                    )),
            ],
            options={
                'unique_together': {('user', 'followed_user')},
            },
        ),
    ]
