# Generated by Django 5.0.6 on 2024-06-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
