# Generated by Django 5.0.6 on 2024-07-04 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(
                choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                default=None, validators=[
                    django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)
                    ]
                ),
        ),
    ]
